name: CICD Actions

on: push

env:
  INTEGRATION_FLOW_ID: New_Flow2
  VERSION: " "

jobs:
  get-integration-flow-runtime:
    runs-on: ubuntu-latest
    steps:
      - name: Get version of Integration Flow deployed
        id: integration_flow_version
        run: |
         URL_RESPONSE=$(curl --ssl-no-revoke -X GET \
          https://b574385atrial.it-cpitrial03-rt.cfapps.ap21.hana.ondemand.com/http/IntegrationRuntimeArtifacts/LatestVersion -H "Authorization: Basic c2ItZDEyOGRmNWMtYjFmZS00MTZmLTljNmYtYzJhOGE4MGUxYmE1IWI5NTQ4fGl0LXJ0LWI1NzQzODVhdHJpYWwhYjE5NjoyYzYwMmViZC0zZGU1LTQ4NmYtYjE4YS04ZWFiM2ZhMWFhZDgkcjNjVWdZS25PMHMwYS1Kb2pUQk1pXzdtbUVNVFZlVDg0YjhDT1dNbzQzMD0=" \
          -H "id: Query_Public_GitHub_Repositories") >> $GITHUB_ENV

          VERSION=$(jq '.entry.properties.Version' <(echo "${URL_RESPONSE}"))

          echo "Fred"

          echo $VERSION

          echo "Fertangg"

          echo "version=${VERSION}" >> $GITHUB_ENV

      - name: Show my version
        run: 'echo "version: ${{ env.version }}"'

      - name: Checkout
        uses: actions/checkout@v3

      - name: List Files After Checkout
        run: |
          pwd
          ls

      - name: Create and Verify New Tag with Integration Flow Version Number
        run: |
          git tag ${{ env.version }}
          git tag

      - name: Get Zipped Contents of Integration Flow in Base64 Encoded String
        run: |
          ZIPPED_CONTENTS=$(curl --ssl-no-revoke -X GET \
          https://b574385atrial.it-cpitrial03-rt.cfapps.ap21.hana.ondemand.com/http/IntegrationRuntimeArtifacts/ZippedContent -H "Authorization: Basic c2ItZDEyOGRmNWMtYjFmZS00MTZmLTljNmYtYzJhOGE4MGUxYmE1IWI5NTQ4fGl0LXJ0LWI1NzQzODVhdHJpYWwhYjE5NjoyYzYwMmViZC0zZGU1LTQ4NmYtYjE4YS04ZWFiM2ZhMWFhZDgkcjNjVWdZS25PMHMwYS1Kb2pUQk1pXzdtbUVNVFZlVDg0YjhDT1dNbzQzMD0=" \
          -H "id: Query_Public_GitHub_Repositories")

          echo "Fred"

          echo $ZIPPED_CONTENTS

          echo "Fertangg"

          echo "base64zip=${ZIPPED_CONTENTS}" >> $GITHUB_ENV
          




   

          